export const GET_SERVERS_SUCCESS = "GET_SERVERS_SUCCESS";
export const GET_SERVERS_FAILED = "GET_SERVERS_FAILED";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_END = "LOADING_END";
