export const GET_CSMASTER_SUCCESS = "GET_CSMASTER_SUCCESS";
export const GET_CSMASTER_FAILED = "GET_CSMASTER_FAILED";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_END = "LOADING_END";
