export const GET_GAMES_DATA_SUCCESS = "GET_EVENTS_DATA_SUCCESS";
export const GET_GAMES_DATA_FAILED = "GET_EVENTS_DATA_FAILED";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_END = "LOADING_END";
