export const GET_EVENTS_DATA_SUCCESS = "GET_EVENTS_DATA_SUCCESS";
export const GET_EVENTS_DATA_FAILED = "GET_EVENTS_DATA_FAILED";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_END = "LOADING_END";

export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILED = "ADD_EVENT_FAILED";

export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const GET_CURRENT_EVENT = "GET_CURRENT_EVENT";
export const GET_SERIAL_SUCCESS = "GET_SERIAL_SUCCESS";
export const GET_SERIAL_LOGS_SUCCESS = "GET_SERIAL_LOGS_SUCCESS";

export const GET_ERROR = "GET_ERROR";
