/* APP MENU */
export const GET_SERVICE_DATA_FAILED = "GET_SERVICE_DATA_FAILED";
export const GET_SERVICE_DATA_SUCCESS = "GET_SERVICE_DATA_SUCCESS";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_END = "LOADING_END";
